### ISSUE TITLE
没有MIPS的so文件

### ISSUE THREAD

**Issue by obarong** [starrtc/starrtc-android-demo#103]
发了个邮件到support，再发一次到issue：
关于starRTC运行在MIPS设备的问题
由于Android的demo没有MIPS的so文件，不能运行在MIPS设备，请问是否能提供mips版本的so？或者是libstarRTC.so和libstarCore.so的源码？

**Comment by elesos** [comment]
暂时不提供该平台so


| |
雷军辉
|
|
admin@elesos.com
|

签名由 网易邮箱大师 定制

在2020年06月28日 09:46，罗锦荣 写道：

发了个邮件到support，再发一次到issue：
关于starRTC运行在MIPS设备的问题
由于Android的demo没有MIPS的so文件，不能运行在MIPS设备，请问是否能提供mips版本的so？或者是libstarRTC.so和libstarCore.so的源码？

**Comment by obarong** [comment]
好的
