### ISSUE TITLE
Android端怎么设置才能连上局域网服务器？

### ISSUE THREAD

**Issue by obarong** [starrtc/starrtc-android-demo#104]
我的服务器是用Docker搭建的，没做过修改，PC端和Android端可以通过IP登录web版demo，可以用聊天室功能。但是像下图那样设置Android端APP不能连上服务器，是没设置对还是服务器没配置好？
![服务器设置](https://user-images.githubusercontent.com/20965086/86072089-63882300-bab3-11ea-8ac8-f64bd40e1065.jpg)

**Comment by obarong** [comment]
看文章 https://www.cnblogs.com/obarong/p/13260626.html

**Comment by elesos** [comment]
谢谢分享




| |
雷军辉
|
|
admin@elesos.com
|

签名由 网易邮箱大师 定制

在2020年07月07日 15:47，罗锦荣 写道：

Closed #104.
