### ISSUE TITLE
有视频远程监控的功能吗

### ISSUE THREAD

**Issue by honggesmile** [starrtc/starrtc-android-demo#111]
首先感谢大神的代码。有视频远程监控的功能吗，改怎样部署

**Comment by elesos** [comment]
直播就是远程监控吧




| |
雷军辉
|
|
admin@elesos.com
|

签名由 网易邮箱大师 定制

在2020年09月01日 17:55，honggesmile 写道：

首先感谢大神的代码。有视频远程监控的功能吗，改怎样部署
