### ISSUE TITLE
VOIP语音通话新增功能-设置超时挂断时长

### ISSUE THREAD

**Issue by VZIKL** [starrtc/starrtc-android-demo#27]
能否增加一个VOIP通话设置自动挂断时长.

**Comment by elesos** [comment]
@VZIKL 是呼叫超时吗？

**Comment by VZIKL** [comment]
@elesos 对的.就是Voip呼叫超时那个.

**Comment by elesos** [comment]
@VZIKL 可以自己控制一下，自己计时到时间挂断就可以了。

**Comment by VZIKL** [comment]
@elesos   我看好像通话到20秒左右就自动超时了,现在有一个情况是要60秒

**Comment by ktomcat** [comment]
这个我们可以调整  等下版本更新   



------------------ 原始邮件 ------------------
发件人: "VZIKL"<notifications@github.com>; 
发送时间: 2019年6月19日(星期三) 上午10:44
收件人: "starrtc/starrtc-android-demo"<starrtc-android-demo@noreply.github.com>; 
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [starrtc/starrtc-android-demo] VOIP语音通话新增功能-设置超时挂断时长 (#27)




@elesos   我看好像通话到20秒左右就自动超时了,现在有一个情况是要60秒

**Comment by VZIKL** [comment]
@ktomcat 
好的 谢谢
