### ISSUE TITLE
调用superRoomManager?.layDownMic崩溃

### ISSUE THREAD

**Issue by OCD0711** [starrtc/starrtc-android-demo#51]
打开app默认开启音频然后调用superRoomManager?.layDownMic关闭会崩溃,实际已关闭成功..
开启时默认关闭音频手动打开择无问题

Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x69676e7d in tid 7193 

![image](https://user-images.githubusercontent.com/25606004/64236873-daa16900-cf2d-11e9-8811-0d8217b73205.png)

**Comment by ktomcat** [comment]
默认开启音频是什么操作？
