### ISSUE TITLE
在超级对讲页面，收不到语音请求，发起语音的那端无回调

### ISSUE THREAD

**Issue by Reginer** [starrtc/starrtc-android-demo#64]
这时候发起语音的那端可不可以回调个  onBusy

**Comment by ktomcat** [comment]
你用demo测试一下  对讲房间是可以收到视频请求的  
如果不行 就是你的demo版本太低了

**Comment by Reginer** [comment]
语音请求，是demo工程，7天前上传的demo

**Comment by Reginer** [comment]
连的是我们的服务器，服务器上部署的服务也都是新版的

**Comment by ktomcat** [comment]
case AEvent.AEVENT_VOIP_REV_CALLING_AUDIO:
                if(MLOC.canPickupVoip){
                    Intent intent = new Intent(this, VoipAudioRingingActivity.class);
                    intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK );
                    intent.putExtra("targetId",eventObj.toString());
                    startActivity(intent);
                }else{
                    MLOC.hasNewVoipMsg = true;
                }
                break;
把这里的if else 去掉就行了  
case AEvent.AEVENT_VOIP_REV_CALLING_AUDIO:
                
                    Intent intent = new Intent(this, VoipAudioRingingActivity.class);
                    intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK );
                    intent.putExtra("targetId",eventObj.toString());
                    startActivity(intent);
                
                break;

**Comment by ktomcat** [comment]
`case AEvent.AEVENT_VOIP_REV_CALLING_AUDIO:
                if(MLOC.canPickupVoip){
                    Intent intent = new Intent(this, VoipAudioRingingActivity.class);
                    intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK );
                    intent.putExtra("targetId",eventObj.toString());
                    startActivity(intent);
                }else{
                    MLOC.hasNewVoipMsg = true;
                }
                break;`
改成
`case AEvent.AEVENT_VOIP_REV_CALLING_AUDIO:
                    Intent intent = new Intent(this, VoipAudioRingingActivity.class);
                    intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK );
                    intent.putExtra("targetId",eventObj.toString());
                    startActivity(intent);
                break;`

**Comment by Reginer** [comment]
XHVoipManagerListener的onAudioCalling回调都不走啊

**Comment by Reginer** [comment]
怪我了怪我了，不知道啥时候又走了 。
