### ISSUE TITLE
换号登录后进入到超级对讲崩溃

### ISSUE THREAD

**Issue by Reginer** [starrtc/starrtc-android-demo#68]
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.starrtc.starrtcsdk.core.StarRtcCore.e()' on a null object reference

**Comment by Reginer** [comment]
com.starrtc.starrtcsdk.api.XHSuperRoomManager.addListener(Unknown Source:4)

**Comment by ktomcat** [comment]
切换账号时 在logout后 增加个几百毫秒的延迟试试

**Comment by Reginer** [comment]
logout之后好久了，只要应用没被杀死再登录进入房间就崩溃。是有哪些类什么东西需要重新release然后再初始化一下么

**Comment by ktomcat** [comment]
用我们最新的demo测试过么？

**Comment by Reginer** [comment]
demo是把应用结束了，我们是相当于跳转到登录页面换个号登录。应用没有结束。
结束的话不崩溃。
