### ISSUE TITLE
即时通讯里怎么不能发照片

### ISSUE THREAD

**Issue by Andkevin** [starrtc/starrtc-android-demo#7]
即时通讯里如果能发送照片就更好了

**Comment by elesos** [comment]
@Andkevin 目前的im是轻量级的，我们重点是音视频通讯。

若有其他需求，将文字换成自己定义的JSON即可。
比如发图片，您可以上传到自己服务器或使用第3方图片存储（如七牛云，阿里云OSS等）将图片上传后，发送url或将url放在json中，接收端解析后自行处理。
