### ISSUE TITLE
怎样搭建自己的服务器，怎么收费呢

### ISSUE THREAD

**Issue by cs1991** [starrtc/starrtc-android-demo#8]
怎样搭建自己的服务器，怎么收费呢

**Comment by elesos** [comment]
@cs1991 服务端很快会放出来，到时可以自行搭建。有问题欢迎加QQ群：807242783

**Comment by elesos** [comment]
服务端现已开放，https://github.com/starrtc/starrtc-server  欢迎大家免费私有部署。

**Comment by nbutGit** [comment]
@elesos 你好 我想问一下 我想用在线教育demo使用到的服务开放了吗   是哪几个服务呀

**Comment by elesos** [comment]
@nbutGit 都开放了，有不会的可以加QQ群咨询。807242783
